# Generated by Django 3.1.2 on 2021-01-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmanager',
            name='detail',
            field=models.TextField(),
        ),
    ]
